version: "3.9"

services:
  db:
    image: postgres:15
    container_name: homefixer-db
    environment:
      POSTGRES_DB: homefixer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    
    container_name: homefixer-web
    command: gunicorn home_fixer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "False"
      DB_NAME: homefixer
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: "True"
      EMAIL_HOST_USER: pateldhruv8404@gmail.com
      EMAIL_HOST_PASSWORD: etti_ztaj_qprs_chej

volumes:
  postgres_data:
